[project]
name = "in-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pytest>=9.1.1",
]

[tool.pytest.ini_options]
pythonpath = [".", "dfs"]
testpaths = [
    "problems/utests",
    "sorting/utests",
    "dfs/utests",
    "two_pointers/basics/utests",
]
